name: 'CernVM-FS (cvmfs)'
description: 'Load the CernVM-FS filesystem at /cvmfs'
branding:
  icon: 'database'
  color: 'blue'
inputs:
  cvmfs_dns_min_ttl:
    description: 'Minimum effective TTL in seconds for DNS queries of proxy server names (not Stratum 1s). Defaults to 1 minute.'
    required: false
    default: '300'
  cvmfs_quota_limit:
    description: 'Soft-limit of the cache in Megabyte.'
    required: false
    default: '25000'
  cvmfs_repositories:
    description: 'Comma-separated list of fully qualified repository names that shall be mountable under /cvmfs.'
    required: false
    default: ''
  cvmfs_http_proxy:
    description: 'Chain of HTTP proxy groups used by CernVM-FS. Necessary. Set to DIRECT if you don’t use proxies.'
    required: false
    default: 'DIRECT'
  cvmfs_use_cdn:
    description: 'Changes the stratum 1 endpoints to caching servers from Cloudflare'
    required: false
    default: 'yes'
  cvmfs_client_profile:
    description: 'Option to choose a suitable proxy automatically'
    required: false
    default: 'single'
runs:
  using: "composite"
  steps: 
    - run: ${{ github.action_path }}/setup-cvmfs.sh
      shell: bash
      env:
        CVMFS_DNS_MIN_TTL: ${{ inputs.cvmfs_dns_min_ttl }}
        CVMFS_QUOTA_LIMIT: ${{ inputs.cvmfs_quota_limit }}
        CVMFS_HTTP_PROXY: ${{ inputs.cvmfs_http_proxy }}
        CVMFS_REPOSITORIES: ${{ inputs.cvmfs_repositories }}
        CVMFS_USE_CDN: ${{ inputs.cvmfs_use_cdn }}
        CVMFS_CLIENT_PROFILE: ${{ inputs.cvmfs_client_profile }}