name: with cvmfs_config_package
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: petricm/github-action-cvmfs@add
      with:
        cvmfs_repositories: 'pilot.eessi-hpc.org'
        cvmfs_http_proxy: 'DIRECT'
        cvmfs_config_package: 'https://github.com/EESSI/filesystem-layer/releases/download/v0.2.3/cvmfs-config-eessi_0.2.3_all.deb'
        run_local_checkout: 'true'
    - name: Setup CernVM-FS
      run: |
        echo "### Dump default.local ###"
        cat /etc/cvmfs/default.local
        echo "### Test /cvmfs/pilot.eessi-hpc.org ###"
        ls /cvmfs/pilot.eessi-hpc.org
        echo "### Test cvmfs_config showconfig pilot.eessi-hpc.org ###"
        cvmfs_config showconfig pilot.eessi-hpc.org
        echo "### Try cvmfs_config probe ###"
        sudo cvmfs_config probe
