name: Test setup-cvmfs action (with cvmfs_repositories)
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: petricm/github-action-cvmfs@main
      with:
        cvmfs_repositories: clicdp.cern.ch
    - name: Setup CernVM-FS
      run: cat /etc/cvmfs/default.local && ls /cvmfs/clicdp.cern.ch/
