name: with cvmfs_http_proxy
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: cvmfs-contrib/github-action-cvmfs@main
      with:
        cvmfs_http_proxy: 'auto'
        run_local_checkout: 'true'
    - name: Setup CernVM-FS
      run: |
        echo "### Dump default.local ###"
        cat /etc/cvmfs/default.local
        echo "### Chech cvmfs_http_proxy is set corretly to auto ###"
        grep auto /etc/cvmfs/default.local
